use Test;

use App::RakuDocToPDF;

my IO::Path $source = $*TMPDIR.add("rakudoc-pdf-{$*PID}.rakudoc");
my IO::Path $output = $*TMPDIR.add("rakudoc-pdf-{$*PID}.pdf");

LEAVE unlink $source if $source.e;
LEAVE unlink $output if $output.e;

spurt $source, q:to/END/;
=begin pod

=head1 TEST PDF

This PDF is generated by the basic App::RakuDocToPDF test.

=begin code
say "PDF";
=end code

=end pod
END

my IO::Path $result = rakudoc-to-pdf(
    $source,
    :$output,
    :media<Letter>,
);

plan 5;

is $result.Str, $output.Str, 'returned requested output path';
ok $output.e, 'PDF file created';
ok $output.s > 100, 'PDF file is not empty';
is $output.slurp(:bin).subbuf(0, 5).decode, '%PDF-', 'file has PDF signature';
ok $output.s, 'generated PDF has content';
