use v6.d;

use Test;

use App::RakuDocToPDF::SlideLayout;

my IO::Path $output = $*TMPDIR.add(
    "rakudoc2pdf-slide-$*PID.pdf"
);

LEAVE {
    $output.unlink if $output.e;
}

my $deck = {
    presentation => {
        title => 'Test Presentation',
    },

    slides => [
        {
            number => 1,

            blocks => [
                {
                    type  => 'heading',
                    level => 1,
                    depth => 0,
                    text  => 'First PDF Slide',
                },
                {
                    type  => 'paragraph',
                    depth => 0,
                    text  => 'This slide was generated by App::RakuDocToPDF.',
                },
            ],
        },
    ],
};

my IO::Path $result = render-slides(
    $deck,
    $output,
);

ok $result.e,
    'slide PDF was created';

ok $result.s > 0,
    'slide PDF is not empty';

is $result.absolute,
    $output.absolute,
    'renderer returns output path';

done-testing;
