use v6.d;

use Test;

use App::RakuDocToPDF::SlideLayout;

my $debug = 0;

my IO::Path $output;

if $debug {
    $output = "rakudoc2pdf-slide.pdf".IO; #-$*PID.pdf".IO;
    say "DEBUG: see pdf '$output'";
}
else {
    $output = $*TMPDIR.add(
        "rakudoc2pdf-slide-$*PID.pdf";
    );
    LEAVE {
        $output.unlink if $output.e;
    }
}

my $heading = {
    type  => 'heading',
    level => 1,
    depth => 0,
    text  => 'First PDF Slide',
};

my $paragraph = {
    type  => 'paragraph',
    depth => 0,
    text  => 'This slide was generated by App::RakuDocToPDF.',
};

my $item = {
    type  => 'item',
    depth => 1,
    text  => 'First bullet item',
};

my $code = {
    type  => 'code',
    depth => 0,
    text  => 'say "Hello, slides!";',
};

my @blocks;
@blocks.push: $heading;
@blocks.push: $paragraph;
@blocks.push: $item;
@blocks.push: $code;

my $slide = {
    number => 1,
    blocks => @blocks.Array,
};

my @slides;
@slides.push: $slide;

my $deck = {
    presentation => {
        title => 'Test Presentation',
    },
    slides => @slides.Array,
};

my IO::Path $result = render-slides(
    $deck,
    $output,
);

ok $result.e,
    'slide PDF was created';

ok $result.s > 0,
    'slide PDF is not empty';

is $result.absolute,
    $output.absolute,
    'renderer returns output path';

done-testing;
