use v6.d;

use Test;

use App::RakuDocToPDF::SlideLayout;

my $heading = {
    type  => 'heading',
    level => 1,
    depth => 0,
    text  => 'First PDF Slide',
};

my $paragraph = {
    type  => 'paragraph',
    depth => 0,
    text  => 'This slide was generated by App::RakuDocToPDF.',
};

my $item = {
    type  => 'item',
    depth => 1,
    text  => 'First bullet item',
};

my $code = {
    type  => 'code',
    depth => 0,
    text  => 'say "Hello, slides!";',
};

my @blocks;
@blocks.push: $heading;
@blocks.push: $paragraph;
@blocks.push: $item;
@blocks.push: $code;

my $slide = {
    number => 1,
    blocks => @blocks.Array,
};

my @lines = layout-slide($slide);

is @lines.elems, 4,
    'four slide lines produced';

is @lines[0]<text>, 'First PDF Slide',
    'heading text preserved';

is @lines[0]<font>, 'heading',
    'heading font selected';

is @lines[0]<size>, 28,
    'heading size selected';

is @lines[0]<x>, 54,
    'heading x position';

is @lines[0]<y>, 558,
    'heading y position';

is @lines[1]<font>, 'body',
    'paragraph uses body font';

is @lines[1]<y>, 510,
    'paragraph follows heading';

is @lines[2]<text>, '- First bullet item',
    'item marker added';

is @lines[2]<x>, 78,
    'item is indented';

is @lines[3]<font>, 'code',
    'code font selected';

is @lines[3]<size>, 14,
    'code size selected';

is @lines[3]<x>, 78,
    'code is indented';

done-testing;
